/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.isetj.guicassandra.gui;

import com.isetj.guicassandra.dao.CassandraConnector;
import com.isetj.guicassandra.jpa.CityEntity;
import com.isetj.guicassandra.gui.LineChartGUI;
import java.awt.BorderLayout;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.City;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
 
/**
 *
 * @author MSellami
 */
public class CovidGUI extends javax.swing.JFrame {
private LineChartGUI ex;


    /**
     * Creates new form CityGUI
     */
    public CovidGUI() {

        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPConnection = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jbConnect = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jtxtNode = new javax.swing.JTextField();
        jtxtPort = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtxtNode2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jbInitDB = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jtxtDbName = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jPCity = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtxtCityID = new javax.swing.JTextField();
        jtxtLongitude = new javax.swing.JTextField();
        jtxtLatitude = new javax.swing.JTextField();
        jSpPopulation = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTbCities = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jbAdd = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jbRefresh = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jtxtCityName = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPConnection.setLayout(null);

        jLabel5.setText("Cassandra Cluster Node");

        jLabel6.setText("Port");

        jbConnect.setText("Connect");
        jbConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConnectActionPerformed(evt);
            }
        });

        jButton6.setText("Cancel");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jtxtNode.setText("127.0.0.1");

        jtxtPort.setText("9042");

        jLabel7.setText("User");

        jtxtNode2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNode2ActionPerformed(evt);
            }
        });

        jLabel8.setText("Password");

        jPasswordField1.setText("jPasswordField1");

        jbInitDB.setText("Init Database");
        jbInitDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInitDBActionPerformed(evt);
            }
        });

        jLabel9.setText("Database");

        jtxtDbName.setText("Covid19DB");
        jtxtDbName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDbNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7)
                        .addComponent(jLabel8)
                        .addComponent(jbConnect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtDbName, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jbInitDB, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtNode2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jtxtNode, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                        .addComponent(jtxtPort)))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtxtNode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtxtPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jtxtDbName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtxtNode2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbConnect)
                    .addComponent(jButton6)
                    .addComponent(jbInitDB))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jPConnection.add(jPanel3);
        jPanel3.setBounds(50, 70, 598, 216);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/covid.jpg"))); // NOI18N
        jLabel17.setText("jLabel17");
        jPConnection.add(jLabel17);
        jLabel17.setBounds(0, 0, 680, 440);

        jTabbedPane1.addTab("Connection", jPConnection);

        jPCity.setBorder(javax.swing.BorderFactory.createTitledBorder("City Infos:"));
        jPCity.setLayout(null);

        jLabel1.setText("City Name:");
        jPCity.add(jLabel1);
        jLabel1.setBounds(6, 59, 162, 14);

        jLabel2.setText("Longitude");
        jPCity.add(jLabel2);
        jLabel2.setBounds(6, 82, 53, 14);

        jLabel3.setText("Latitude");
        jPCity.add(jLabel3);
        jLabel3.setBounds(6, 107, 39, 14);

        jLabel4.setText("Population");
        jPCity.add(jLabel4);
        jLabel4.setBounds(6, 138, 50, 14);

        jtxtCityID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCityIDActionPerformed(evt);
            }
        });
        jPCity.add(jtxtCityID);
        jtxtCityID.setBounds(71, 22, 207, 20);

        jtxtLongitude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtLongitudeActionPerformed(evt);
            }
        });
        jPCity.add(jtxtLongitude);
        jtxtLongitude.setBounds(71, 79, 207, 20);
        jPCity.add(jtxtLatitude);
        jtxtLatitude.setBounds(71, 104, 207, 20);

        jSpPopulation.setModel(new javax.swing.SpinnerNumberModel(450.0d, null, null, 1.0d));
        jPCity.add(jSpPopulation);
        jSpPopulation.setBounds(66, 135, 87, 20);

        jTbCities.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jTbCities.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "City ID", "City Name", "Longitude", "Latitude", "Population"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTbCities);

        jPCity.add(jScrollPane1);
        jScrollPane1.setBounds(20, 220, 636, 90);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Operations"));

        jbAdd.setText("Add");
        jbAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAddActionPerformed(evt);
            }
        });

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Delete");

        jButton4.setText("Find");

        jbRefresh.setText("Refresh");
        jbRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jbRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                    .addComponent(jbAdd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jbAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbRefresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4))
        );

        jPCity.add(jPanel1);
        jPanel1.setBounds(485, 22, 167, 166);

        jLabel10.setText("City ID");
        jPCity.add(jLabel10);
        jLabel10.setBounds(6, 25, 61, 14);

        jtxtCityName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCityNameActionPerformed(evt);
            }
        });
        jPCity.add(jtxtCityName);
        jtxtCityName.setBounds(71, 53, 207, 20);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/covid.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        jPCity.add(jLabel11);
        jLabel11.setBounds(0, 2, 680, 570);

        jTabbedPane1.addTab("Cities", jPCity);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 685, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Covid-19", jPanel2);

        jPanel4.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Nombre de nouveaux cas:");
        jPanel4.add(jLabel13);
        jLabel13.setBounds(10, 100, 190, 20);

        jLabel14.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Nombre total des cas:");
        jPanel4.add(jLabel14);
        jLabel14.setBounds(30, 170, 151, 17);
        jPanel4.add(jTextField1);
        jTextField1.setBounds(230, 90, 157, 32);
        jPanel4.add(jTextField2);
        jTextField2.setBounds(230, 160, 157, 28);
        jPanel4.add(jTextField3);
        jTextField3.setBounds(290, 230, 97, 31);

        jLabel15.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Pourcentage:");
        jPanel4.add(jLabel15);
        jLabel15.setBounds(180, 240, 100, 17);

        jButton1.setText("Statique");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);
        jButton1.setBounds(420, 230, 90, 32);

        jButton5.setText("Afficher le graphe");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton5);
        jButton5.setBounds(270, 320, 150, 32);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/covid19.jpg"))); // NOI18N
        jLabel12.setText("jLabel12");
        jPanel4.add(jLabel12);
        jLabel12.setBounds(0, -18, 680, 510);

        jTabbedPane1.addTab("Statistiques", jPanel4);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(10, 11, 690, 506);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtCityIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCityIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCityIDActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jtxtNode2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNode2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNode2ActionPerformed

    private void jbConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConnectActionPerformed
        // TODO add your handling code here:
        try {
            CassandraConnector.connect(jtxtNode.getText(), Integer.parseInt(jtxtPort.getText()), "", "");
            JOptionPane.showMessageDialog(this, "Connection with Success", "Connection", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            System.out.print(e);
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error Connection", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_jbConnectActionPerformed

    private void jbInitDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInitDBActionPerformed
        try {
            CassandraConnector.createKeyspace(jtxtDbName.getText(), "SimpleStrategy", 1);
            JOptionPane.showMessageDialog(this, "Database Initialization with Success", "Connection", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            System.out.print(e);
            JOptionPane.showMessageDialog(this, e.getMessage(), "Database Initialization Error", JOptionPane.ERROR_MESSAGE);

        }

    }//GEN-LAST:event_jbInitDBActionPerformed

    private void jtxtDbNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDbNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDbNameActionPerformed

    private void jbAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAddActionPerformed
        // TODO add your handling code here:
        City city = new City(Integer.parseInt(jtxtCityID.getText()), this.jtxtCityName.getText(), Double.parseDouble(this.jtxtLongitude.getText()), Double.parseDouble(this.jtxtLatitude.getText()), Double.parseDouble(this.jSpPopulation.getValue().toString()));
        try {
            //insertion d'une nouvelle ville
            CityEntity.insertCity(city, this.jtxtDbName.getText());
            //recuperer tous les cities inseres dans la bases
            List<City> Cities = CityEntity.selectAll(this.jtxtDbName.getText());
            //Creer un model pour la table/schema
            DefaultTableModel model = new DefaultTableModel(new Object[]{"ID City", "City Name", "Longitude", "Latitude", "Population"}, 0);
            for (City City : Cities) {
                model.addRow(new Object[]{City.getIDCity(), City.getCityName(), City.Longitude, City.Latitude, City.getPopulation()});
            }
            jTbCities.setModel(model);
            JOptionPane.showMessageDialog(this, "Adding City with Success", "Connection", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            System.out.print(e);
            JOptionPane.showMessageDialog(this, e.getMessage(), "Database Insert Error", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_jbAddActionPerformed

    private void jtxtCityNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCityNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCityNameActionPerformed

    private void jbRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRefreshActionPerformed

 try {
            
            List<City> Cities = CityEntity.selectAll(this.jtxtDbName.getText());
            DefaultTableModel model = new DefaultTableModel(new Object[]{"ID City", "City Name", "Longitude", "Latitude", "Population"}, 0);
            for (City City : Cities) {
                model.addRow(new Object[]{City.getIDCity(), City.getCityName(), City.Longitude, City.Latitude, City.getPopulation()});
            }
            jTbCities.setModel(model);
            JOptionPane.showMessageDialog(this, "Refresh City with Success", "Connection", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            System.out.print(e);
            JOptionPane.showMessageDialog(this, e.getMessage(), "Database Refresh Error", JOptionPane.ERROR_MESSAGE);

        }        // TODO add your handling code here:
    }//GEN-LAST:event_jbRefreshActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jtxtLongitudeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtLongitudeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtLongitudeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                                        
        // TODO add your handling code here:
      
	String nombre1String = jTextField1.getText();//On r�cup�re la valeur dans le premier champ
	int nvc = Integer.parseInt(nombre1String);//On convertit cette valeur en un nombre
	
	String nombre2String = jTextField2.getText();//On r�cup�re la valeur dans le deuxi�me champ
	int total = Integer.parseInt(nombre2String);//On convertit cette valeur en un nombre
	
	int resultat = (nvc *100/ total);
	jTextField3.setText( resultat+"%");

                 // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
                              ex= new LineChartGUI();
 ex.setVisible(true);
 
 
 
     //DefaultCategoryDataset barchartdata=new DefaultCategoryDataset();
     //barchartdata.setValue(0,"Janfier","fevrier");
     //barchartdata.setValue(50,"fevrier","mars");
     //barchartdata.setValue(500,"mars","avril");
     //barchartdata.setValue(1051,"avril","mai");
     
     
     //JFreeChart barchart= ChartFactory.createBarChart("hgvtuf", "gvgjjh", "cfgjfccjgc", barchartdata,PlotOrientation.VERTICAL,false,true,false);
//CategoryPlot barchrt= barchart.getCategoryPlot();
//barchrt.setRangeGridlinePaint(Color.ORANGE);
//ChartPanel barPanel=new ChartPanel(barchart);
 //jPanel5.removeAll();
 //jPanel5.add(barPanel,BorderLayout.CENTER);
 //jPanel5.validate();
 
 


            
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CovidGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CovidGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CovidGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CovidGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CovidGUI c= new CovidGUI();
                c.setSize(400,400);
                c.setTitle("Covid-19");
                new CovidGUI().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPCity;
    private javax.swing.JPanel jPConnection;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpPopulation;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTbCities;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton jbAdd;
    private javax.swing.JButton jbConnect;
    private javax.swing.JButton jbInitDB;
    private javax.swing.JButton jbRefresh;
    private javax.swing.JTextField jtxtCityID;
    private javax.swing.JTextField jtxtCityName;
    private javax.swing.JTextField jtxtDbName;
    private javax.swing.JTextField jtxtLatitude;
    private javax.swing.JTextField jtxtLongitude;
    private javax.swing.JTextField jtxtNode;
    private javax.swing.JTextField jtxtNode2;
    private javax.swing.JTextField jtxtPort;
    // End of variables declaration//GEN-END:variables
}
